"""changed type to datetime.

Revision ID: 52fcc8e519a9
Revises: 61277c7dfb9a
Create Date: 2026-04-10 11:30:35.809899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fcc8e519a9'
down_revision = '61277c7dfb9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Force PostgreSQL to do the conversion using raw SQL
    op.execute(
        "ALTER TABLE url_db ALTER COLUMN timestamp TYPE TIMESTAMP WITHOUT TIME ZONE USING timestamp::timestamp without time zone"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_db', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
