"""Add foreign key to urls.

Revision ID: 61277c7dfb9a
Revises: 3d1754cfb01a
Create Date: 2026-04-10 10:35:21.804157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61277c7dfb9a'
down_revision = '3d1754cfb01a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_db', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'url_db', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('url_db', 'user')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('url_db', sa.Column('user', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'url_db', type_='foreignkey')
    op.drop_column('url_db', 'user_id')
    # ### end Alembic commands ###
