"""empty message.

Revision ID: 82acd783d33b
Revises: c733df4a1cdd
Create Date: 2026-04-02 15:09:28.163064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82acd783d33b'
down_revision = 'c733df4a1cdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
