"""hashed password not unique.

Revision ID: 3d1754cfb01a
Revises: 5bddca1bb481
Create Date: 2026-04-08 17:28:46.986323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1754cfb01a'
down_revision = '5bddca1bb481'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_hashed_password'), table_name='user')
    op.create_index(op.f('ix_user_hashed_password'), 'user', ['hashed_password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_hashed_password'), table_name='user')
    op.create_index(op.f('ix_user_hashed_password'), 'user', ['hashed_password'], unique=True)
    # ### end Alembic commands ###
