"""empty message.

Revision ID: 8baf36d7ff7a
Revises: 2b7380507a71
Create Date: 2026-04-02 14:31:49.001799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8baf36d7ff7a'
down_revision = '2b7380507a71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_db',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('total_img', sa.Integer(), nullable=True),
    sa.Column('with_alt', sa.Integer(), nullable=True),
    sa.Column('without_alt', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('dummy_model', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dummy_model', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_table('url_db')
    # ### end Alembic commands ###
